articles/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 30 15:21:19 2020

@author: hamel
"""

#from . import views
from django.urls import path

from django.conf.urls import url
from articles import views
# SET THE NAMESPACE!
app_name = 'articles'

urlpatterns = [
    url(r'^post/$', views.post, name = 'post'),
    path('post_list/', views.PostList.as_view(), name='post_list'),
    #url(r'^register/$',views.register,name='register'),
    #path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('<slug:slug>/', views.post_detail, name='post_detail')    
    #path('post/', views.post, name='post'),
]

bibugn/urls.py
# bibugn/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from fundraising import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^account/$', views.account, name = 'account'),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    path('fundraising/',include('fundraising.urls')),
    path('articles/',include('articles.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^signup/$',views.signup, name='signup'),
]

fundraising/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May  4 16:38:11 2020

@author: hamel
"""
# fundraising/urls.py
from django.urls import path
from django.conf.urls import url
from fundraising import views
#from .views import detail_view, update_view
# SET THE NAMESPACE!
app_name = 'fundraising'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^add_bio/$',views.add_bio,name='add_bio'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^promise/$', views.promise, name = 'promise'),
    url(r'^pay/$', views.pay, name = 'pay'),
    
    path('detail_view/', views.detail_view, name = 'detail_view' ), 
    #path('<p>/update', views.update_view, name = 'update_view' ),
    path('update/', views.update_view, name = 'update_view' ),
    path('total_promise/', views.total_promise, name = 'total_promise' ),
    path('total_payment/', views.total_payment, name = 'total_payment' ),
    path('view_total_promise/', views.view_total_promise, name = 'view_total_promise'), 
    path('view_total_payment/', views.view_total_payment, name = 'view_total_payment'),
    path('getpdf_promise_total/', views.getpdf_promise_total, name = 'getpdf_promise_total'),
    
   
]

articles/models.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 30 15:05:03 2020

@author: hamel
"""

from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0,"Draft"),
    (1,"Publish")
)

class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

articles/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 12 12:04:33 2020

@author: hamel
"""

from django import forms
from articles.models import Post

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields= '__all__'
        prepopulated_fields = {'slug': ('title',)}
        
        
from .models import Comment
#from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

articles/views.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 30 15:20:16 2020

@author: hamel
"""

from django.views import generic
#from articles.models import Post


from .models import Post
from articles.forms import CommentForm, PostForm
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib import messages

class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'articles/articlespost_list.html'

def post_detail(request, slug):
    template_name = 'articles/articlespost_detail.html'
    post = get_object_or_404(Post, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})

# functions to get Users post
def post(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            #user_form = UserForm(data=request.POST)
            post_form = PostForm(data=request.POST)
            if post_form.is_valid():
                #user = user_form.save()
                post = post_form.save()
                post.author = request.auther
                post = post_form.save(commit=False)
                #w.user =user
                post.save()
                #registered = True
                messages.success(request, 'Your article was posted successfully!')
                return redirect('index')
            else:
                print(post_form.errors)
        else:
            return redirect('/fundraising/user_login')
    else:
        #user_form = UserForm()
        post_form = PostForm()
    return render(request, 'articles/post.html', {'post_form': post_form})

templates/articles/articlesbase.html
{% load static %}
<!DOCTYPE html>
{# you can leave this line okay!  {% load bootstrap4 %}  #}

<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Debre Markos Town and Surrounding COVID-19 Fundraising</title>

        <header class="masthead" >
            <div class="overlay"></div>
            <div class="container">
              <div class="row">
                <div class=" col-md-8 col-md-10 mx-auto">
                  <div class="site-heading">
                    <h1 class=" site-heading my-4 mt-3 text-black"> Debre Markos Town and Surrounding COVID-19 Fundraising Campaign</h1>
                    <p class="text-light">Compassion is much better than Every thing..! &nbsp
                    </p>
                </div>
                    </div>
                  </div>               
            </div>
          </header>


    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">



    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
</head>

<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Main Menu</h3>
            </div>

            <ul class="list-unstyled components">
                
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="{% url 'index' %}">Latest News</a>
                        </li>
                        <li>
                            <a href="{% url 'articles:post_list' %}">Posts</a>
                        </li>
                        <li>
                            <a href="{% url 'fundraising:add_bio' %}">Add Your Bio Here. It is optional</a>
                        </li>
                        <li>
                            <a href="{% url 'fundraising:promise' %}">Promise Here</a>
                        </li>
                        <li>

                            <a href="{% url 'fundraising:update_view' %}">Click Here to update your promise</a>
                        </li>
                        <li>
                            <a href="{% url 'fundraising:pay' %}">Pay Here</a>
                        </li>
                        <li>
                            <a href="#">Update your Payment Here</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">About Us</a>
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Messages</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Message Inbox</a>
                        </li>
                        <li>
                            <a href="#">Message Outbox</a>
                        </li>
                        <li>
                            <a href="#">Compose Message</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'fundraising:total_promise' %}">Total promise in ETB</a>
                </li>
                <li>
                    <a href="{% url 'fundraising:total_payment' %}">Total Payment in ETB</a>
                </li>
                <li>
                    <a href="#">Policy</a>
                </li>
                <li>
                    <a href="#">Contact Us</a>
                </li>
            </ul>

            <ul class="list-unstyled CTAs">
                <li>
                    <a href="{% url 'fundraising:view_total_promise' %}" class="download">see who Promised</a>
                </li>
                <li>
                    <a href="{% url 'fundraising:view_total_payment' %}" class="download">See who Paid</a>
                <li>
                    <a href="{% url 'fundraising:getpdf_promise_total' %}" class="download">Promise in PDF</a>
                </li>
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'signup' %}">Signup Here</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'fundraising:user_login' %}">Login Here</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Change Password</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Notification</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Chat Here</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

        

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>
{% block content %}
{% endblock %}

</body>

</html>

templates/articles/articlespost_detail.html
{% extends "articles/articlesbase.html" %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ post.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ post.content | safe }}</p>
      </div>
    </div>
    
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
        <!-- comments -->
        <h2>{{ comments.count }} comments</h2>

        {% for comment in comments %}
        <div class="comments" style="padding: 10px;">
          <p class="font-weight-bold">
            {{ comment.name }}
            <span class=" text-muted font-weight-normal">
              {{ comment.created_on }}
            </span>
          </p>
          {{ comment.body | linebreaks }}
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-md-8 card mb-4  mt-3 ">
      <div class="card-body">
{% if user.is_authenticated %}
        {% if new_comment %}
        <div class="alert alert-success" role="alert">
          Your comment is awaiting moderation
        </div>
        {% else %}
        <h3>Leave a comment</h3>
        <form method="post" style="margin-top: 1.3em;">
          {{ comment_form.as_p }}
          {% csrf_token %}
          <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
        {% endif %}
 {% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/articles/articlespost_list.html
{% extends "articles/articlesbase.html" %} 
{% load static %}
{% block content %}


    
        
            <div class="container">
                <div class="row">
      
              <!-- Blog Entries Column -->
              <div class="col-md-8 mt-3 left">
                    {% for post in post_list %}
                <div class="card mb-4" >
                  <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>

                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'articles:post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                  </div>
                 
                </div>
                {% endfor %}            
        </div>


       
               
      
              <!-- Here ou can post your what is in your mind -->
            
                   
                
                  <div class="card-body">
                  
                   
                    <a href="{% url 'articles:post' %}" class="btn btn-info">Post yours</a>
                  </div>
                 
              
                           
        </div>

{%endblock%}

templates/articles/latest_news.html
{% extends "articles/articlesbase.html" %} 
{% load static %}
{% block content %}


  

<h2>World Wide Basic News About COVID-19</h2>
            <p>Reported Cases and Deaths by Country, Territory, or Conveyance
The coronavirus COVID-19 is affecting 213 countries and territories around the world and 2 international conveyances. The day is reset after midnight GMT+0. The list of countries and territories and their continental regional classification is based on the United Nations Geoscheme. Sources are provided under "Latest Updates". Learn more about Worldometer's COVID-19 data.</p>

            <div class="line"></div>

            <h2>COVID Specific News About Ethiopia</h2>
            <p>#COVID19Ethiopia latest: Fourteen (14) people have tested positive for #COVID19 out of 3271 laboratory tests conducted in the last 24 hrs, bringing the total confirmed number in Ethiopia to 365.</p>

<p>Four (4) people have also recovered, bringing the total recovered number to 120.

Of the 14 who tested positive today six (6) have travel history, seven (7) have contact traces with previous case & one (1) has neither of both. Among these nine (9) are from #AddisAbeba (Seven of these are due to contact with previous case, one is a cross country truck driver, and the other one is the one who has neither travel nor contact).

One is from #Tigray, #Mekelle quarantine center, and one is from #Oromia. The patients in both cases are cross country truck drivers.

The last three are from #Jigjiga quarantine center in #Somali region.</p>
<p>
#Correction from the Ministry of Health: One case which was announced yesterday from #Ataye quarantine center in #Amhara region, is an old case which was already counted. Therefore yesterday's tally is 34, instead of 35.</p>

            <div class="line"></div>

            <h2>Motivation Behind</h2>
            <p>The motivation behind the development of this application is behind Bibugn COVID-19 Fundraising, initiated by those originated from that village. It was founded before a month and could collect worth a value of more than 500,000 ETB. it is fantastic..</p>

            <div class="line"></div>

            <h3>Features</h3>
            <p>This application being developed is supposed mainly to authomatically register those who promised and payed for the fundraising, the main motivation behind. it also registers all generations of the village and displays posts, news, etc. The user can rget registered, add bios, comment, post articles, promises, pays for what he/she promised on behalf of something, he would like.</p>
      

{%endblock%}

templates/articles/post.html
{% load static %}
<html>
<head><title> Post Here </title> 

<!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
  <div class="container">
    <div class="jumbotron">
      
        <h1>you can post here {{ user.first_name}}  </h1>
        <h3>Just fill out the form.</h3>
{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
        
         <form enctype="multipart/form-data" method="POST">
             {% csrf_token %}         
           
              {{ post_form.as_p }}
          
            <center>         
          <input type="submit" name="" value="post Here" class="btn btn-primary">  </center> 
        </form>
        
    
    </div>
  </div>

</body>
</html>